### ISSUE TITLE
Modules missing from setup.py

### ISSUE THREAD

**Issue by dentalfloss1** [transientskp/pyse#36]
There seems to be a few modules missing from setup.py that generate errors like the one below. I ran into these errors with dask, dask-distributed, and psutil.
```
Traceback (most recent call last):
  File "/mnt/Gunther/Software/pysenv/bin/pyse", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/mnt/Gunther/Software/pyse/scripts/pyse", line 32, in <module>
    from sourcefinder.accessors import open as open_accessor
  File "/mnt/Gunther/Software/pyse/sourcefinder/accessors/__init__.py", line 16, in <module>
    from sourcefinder.image import ImageData
  File "/mnt/Gunther/Software/pyse/sourcefinder/image.py", line 18, in <module>
    import dask.array as da
ModuleNotFoundError: No module named 'dask'

```

**Comment by HannoSpreeuw** [comment]
Ah, I think I understand how this happened. 
I have been developing pyse using a Pipfile in a parent directory.
With `export PYTHONPATH=GH`, GH being the folder where the git clone of pyse sits.
Never used `setup.py`, instead I ran
```
pipenv install
```
and
```
pipenv run python pyse.py ......
```
or
```
pipenv shell
python pyse.py ......
```
Would we want to go for virtual environments and leave the setup.py behind?

**Comment by HannoSpreeuw** [comment]
I did some reading on setup.py vs pipenv and this [SO discussion](https://stackoverflow.com/questions/47227406/pipenv-vs-setup-py) is interesting. 
What we need to establish is if pyse is a library or an application.
I would say it is an application, since we advertise it as a [standalone tool](https://tkp.readthedocs.io/en/release4.0/tools/pyse.html)
_If you're building an application, then pipenv is the only thing you need._

However, as part of TraP, you could consider pyse a library, but the sourcefinder code for TraP lives inside the [tkp repo](https://github.com/transientskp/tkp/tree/master/tkp/sourcefinder) as a duplicate, it is not imported as a library.

So I think we could switch from setup.py to pipenv.
