### ISSUE TITLE
Add developer documentation

### ISSUE THREAD

**Issue by suvayu** [transientskp/pyse#59]
- [x] building packages
- [x] versioning
- [x] running the test suite
- [x] running linters/static analysers/formatters
- [x] running scripts

**Comment by suvayu** [comment]
@HannoSpreeuw could you check the README, do you think it's missing something.  I was in the flow, and forgot to create a PR :stuck_out_tongue:

**Comment by HannoSpreeuw** [comment]
Looks great. Nice and complete.

`while development` ---> `while developing`?

`if you want to trigger only the build hooks`.....
"build hooks" have a high abstraction level for me. Perhaps a few extra words about what they are?

The `hatch run test:pytest --no-cov` may be relevant for PyCharm users, since [you cannot debug tests from pytest in PyCharm if you have coverage enabled](https://youtrack.jetbrains.com/issue/PY-20186). But adding that to this README  may not be appropriate.

**Comment by suvayu** [comment]
> But adding that to this README may not be appropriate.

This readme update is until I get around to #60. It would fit nicely in an extended developer docs.
