### ISSUE TITLE
Pyse.py command line options need unit-testing

### ISSUE THREAD

**Issue by timstaley** [transientskp/pyse#68]
cf https://redmine.astron.nl/lofar_issuetracker/issues/6730

These are currently untested, which previously led to a bug lying undiscovered for 6 months (https://redmine.astron.nl/lofar_issuetracker/issues/6725)

**Comment by AntoniaR** [comment]
Unfortunately, it seems like there is no longer a record of these issues. Additionally, PySE has gone through some major changers since the issue was posted so it's not clear if this is still an issue. I suggest that we then close this issue for now and make a new issue if/when we come across an error.
